apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: registry-server
  labels:
    app: registry-server
    life: prod
spec:
  serviceName: registry-headless
  selector:
    matchLabels:
      app: registry-server
      life: prod
#  strategy:
#    type: RollingUpdate
#    rollingUpdate:
#      maxSurge: 1
#      maxUnavailable: 1
  replicas: 2
  template:
    metadata:
      name: registry-server
      labels:
        app: registry-server
        life: prod
    spec:
      restartPolicy: Always
      containers:
      - name: registry-server
        imagePullPolicy: Always
        image: alaien/registry-server
        ports:
        - containerPort: 8761
        env:
        - name: HEAP_MEM
          value: 256m
        - name: OTHER_SERVERS_URL
          value: http://test:test@registry-server-0.registry-headless:8761/eureka,http://test:test@registry-server-1.registry-headless:8761/eureka
        resources:
          requests:
            memory: "256Mi"
            cpu: "10m"
          limits:
            memory: "512Mi"
            cpu: "1000m"

---

apiVersion: v1
kind: Service
metadata:
  name: registry-server
  labels:
    app: registry-server
    life: prod
spec:
  selector:
    app: registry-server
    life: prod
  ports:
  - name: port
    port: 80
    targetPort: 8761

---

apiVersion: v1
kind: Service
metadata:
  name: registry-headless
  labels:
    app: registry-headless
    life: prod
spec:
  selector:
    app: registry-server
    life: prod
  clusterIP: None
  ports:
  - name: port
    port: 8761
    targetPort: 8761
