apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: registry-server
  labels:
    app: eureka
spec:
  serviceName: registry-server-internal
  selector:
    matchLabels:
      app: eureka
  replicas: 2
  template:
    metadata:
      name: registry-server
      labels:
        app: eureka
    spec:
      restartPolicy: Always
      containers:
      - name: registry-server
        image: alaien/eureka-test
        imagePullPolicy: Always
        env:
        - name: HEAP_MEM
          value: 256m
        - name: OTHER_SERVERS_URL
          value: http://eagleeye:eagleeye2019@registry-server-0.registry-headless:8761/eureka,http://eagleeye:eagleeye2019@registry-server-1.registry-headless:8761/eureka
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: registry-headless
  labels:
    app: eureka
spec:
  selector:
    app: eureka
  clusterIP: None
  ports:
  - port: 8761
    targetPort: 8761


---

apiVersion: v1
kind: Service
metadata:
  name: registry-server
  labels:
    app: eureka
spec:
  selector:
    app: eureka
  type: NodePort
  ports:
  - port: 80
    targetPort: 8761
    nodePort: 30000