apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: config-server
  labels:
    app: config-server
spec:
  selector:
    matchLabels:
      app: config-server
  replicas: 2
  template:
    metadata:
      name: config-server
      labels:
        app: config-server
    spec:
      restartPolicy: Always
      containers:
      - name: config-server
        image: alaien/config-server
        imagePullPolicy: Always
        env:
        - name: HEAP_MEM
          value: 256m
        - name: REGISTRY_SERVERS_URL
          value: http://eagleeye:eagleeye2019@config-server-0.registry-headless:8761/config-server,http://eagleeye:eagleeye2019@config-server-1.registry-headless:8761/config-server
        ports:
        - containerPort: 3000


---

apiVersion: v1
kind: Service
metadata:
  name: config-server
  labels:
    app: config-server
spec:
  selector:
    app: config-server
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 3000