apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: config-server
  labels:
    app: config-server
spec:
  selector:
    matchLabels:
      app: config-server
  replicas: 1
  template:
    metadata:
      name: config-server
      labels:
        app: config-server
    spec:
      restartPolicy: Always
      containers:
      - name: config-server
        image: alaien/sample-config
        imagePullPolicy: Always
        env:
        - name: HEAP_MEM
          value: 256m
        - name: REGISTRY_SERVERS_URL
          value: http://test:test@registry-server/eureka
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "10m"
            memory: "256Mi"
          limits:
            cpu: "200m"
            memory: "300Mi"

---

apiVersion: v1
kind: Service
metadata:
  name: config-server
  labels:
    app: config-server
spec:
  selector:
    app: config-server
  ports:
  - port: 80
    targetPort: 3000