apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
    life: prod
spec:
  selector:
    matchLabels:
      app: grafana
      life: prod
  replicas: 1
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
        life: prod
    spec:
      restartPolicy: Always
      containers:
      - name: grafana
        image: $DOCKER_REPO/grafana
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: GF_AUTH_PROXY_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        resources:
          requests:
            cpu: "20m"
          limits:
            memory: "1000Mi"

---

apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
    life: prod
spec:
  selector:
    app: grafana
    life: prod
  ports:
  - name: grafana
    port: 80
    targetPort: 3000
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
