apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
    life: prod
spec:
  selector:
    matchLabels:
      app: elasticsearch
      life: prod
  replicas: 1
  template:
    metadata:
      name: elasticsearch
      labels:
        app: elasticsearch
        life: prod
    spec:
      restartPolicy: Always
      containers:
      - name: elasticsearch
        image: $DOCKER_REPO/elasticsearch
        imagePullPolicy: Always
        ports:
        - name: elasticsearch
          containerPort: 9200
        volumeMounts:
        - name: elastic-data
          mountPath: /usr/share/elasticsearch/data
        resources:
          requests:
            cpu: "20m"
          limits:
            memory: "2000Mi"
      volumes:
      - name: elastic-data
        persistentVolumeClaim:
          claimName: elasticsearch-claim

---

apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
    life: prod
spec:
  selector:
    app: elasticsearch
    life: prod
  ports:
  - name: elasticsearch
    port: 80
    targetPort: 9200