server:
  port: 30000

spring:
  application:
    name: api-geteway
zuul:
  prefix: /api
  retryable: true
  routes:
    hello-service:
      path: /hello-service/**
      serviceId: hello-service

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka
