apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: registry-server
  labels:
    app: registry-server
spec:
  serviceName: registry-headless
  selector:
    matchLabels:
      app: registry-server
  replicas: 2
  template:
    metadata:
      name: registry-server
      labels:
        app: registry-server
    spec:
      restartPolicy: Always
      containers:
      - name: registry-server
        image: alaien/sample-registry
        imagePullPolicy: Always
        env:
        - name: HEAP_MEM
          value: 256m
        - name: REGISTRY_SERVERS_URL
          value: http://test:test@registry-server-0.registry-headless:8761/eureka,http://test:test@registry-server-1.registry-headless:8761/eureka
        ports:
        - containerPort: 8761
        resources:
          requests:
            cpu: "10m"
            memory: "256Mi"
          limits:
            cpu: "200m"
            memory: "300Mi"

---

apiVersion: v1
kind: Service
metadata:
  name: registry-headless
  labels:
    app: registry-server
spec:
  selector:
    app: registry-server
  clusterIP: None
  ports:
  - port: 8761
    targetPort: 8761

---

apiVersion: v1
kind: Service
metadata:
  name: registry-server
  labels:
    app: registry-server
spec:
  selector:
    app: registry-server
  ports:
  - name: port
    port: 80
    targetPort: 8761