spring:
  application:
    name: gateway

server:
  port: 9000

zuul:
#  prefix: /api
  retryable: false
  routes:
    config-server:
      path: /gateway/config/**
      serviceId: config-server
#    provider:
#      path: /gateway/provider/**
#      serviceId: provider
#      sensitiveHeaders: Access-Control-Allow-Origin,Access-Control-Allow-Methods

management:
  endpoints:
    web:
      exposure:
        include: "*"