spring:
  application:
    name: gateway

server:
  port: 9000

zuul:
  ribbon-isolation-strategy: thread
  thread-pool:
    use-separate-thread-pools: true
#  prefix: /api
  retryable: false
  routes:
    config-server:
      path: /gateway/config/**
      serviceId: config-server
    hello-service:
      sensitiveHeaders: Access-Control-Allow-Origin,Access-Control-Allow-Methods
      path: /gateway/hello-service/**
      serviceId: hello-service

management:
  endpoints:
    web:
      exposure:
        include: "*"

ribbon:
  OkToRetryOnAllOperations: false
  ReadTimeout: 10000
  ConnectTimeout: 1000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1

hystrix:
  command:
    hello-service:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 10000
      circuitBreaker:
        sleepWindowInMilliseconds: 5000
        requestVolumeThreshold: 10
        errorThresholdPercentage: 50